name: CI/CD Pipeline

on: 
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: email-bot

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:latest .

    - name: Run basic test (start app.py in container)
      run: | 
        docker run --rm -d -p 7860:7860 --name test-app ${{ env.DOCKER_IMAGE_NAME }}:latest
        sleep 10 # Give the app some time to start
        docker logs test-app
        docker stop test-app

  push-to-dockerhub:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image for push
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
